//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: VoiceCommand.proto
using System.ComponentModel;
using System.Text;
namespace VoiceCommand
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"VoiceCommand")]
    public partial class VoiceCommandProto : global::ProtoBuf.IExtensible
    {
        public VoiceCommandProto() { }

        private string _opcode;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"opcode", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string opcode
        {
            get { return _opcode; }
            set { _opcode = value; }
        }
        private string _culture;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"culture", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string culture
        {
            get { return _culture; }
            set { _culture = value; }
        }
        private readonly global::System.Collections.Generic.List<int> _args = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(3, Name = @"args", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
        public global::System.Collections.Generic.List<int> args
        {
            get { return _args; }
        }

        private readonly global::System.Collections.Generic.List<VoiceCommandProto.word_result> _words = new global::System.Collections.Generic.List<VoiceCommandProto.word_result>();
        [global::ProtoBuf.ProtoMember(4, Name = @"words", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<VoiceCommandProto.word_result> words
        {
            get { return _words; }
        }

        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"word_result")]
        public partial class word_result : global::ProtoBuf.IExtensible
        {
            public word_result() { }

            private string _word;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"word", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public string word
            {
                get { return _word; }
                set { _word = value; }
            }
            private float _confidence;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"confidence", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
            public float confidence
            {
                get { return _confidence; }
                set { _confidence = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }

    }

}